/**
 * Asset registry for the PixiJS renderer. Paths resolve from Next.js `public/`.
 *
 * Robot/effect/marker sprites are the "Foundry Plate" production set
 * (2026-07-16); robot files are generated by scripts/generate-robot-assets.mjs
 * and documented in docs/asset-manifest.md. Do not hand-edit generated SVGs.
 */

import type { Posture, RobotClass, Terrain } from "../engine/types";

/**
 * Raster density for SVG-sourced textures. The tile SVGs are 24-unit
 * viewBoxes; at 1× Pixi would bake 24px bitmaps that turn to mush once the
 * movie's CSS zoom (up to 3×) stretches them. 4× covers max zoom on a 2×
 * display while sprites keep their layout size (the texture only gets denser).
 */
export const SVG_TEXTURE_RESOLUTION = 4;

/** Assets.load descriptor that rasterizes an SVG at SVG_TEXTURE_RESOLUTION.
 *  The cache key stays the bare URL, so `Assets.get(url)` still resolves. */
export const highResSvg = (url: string) => ({
  src: url,
  data: { resolution: SVG_TEXTURE_RESOLUTION },
});

export const TERRAIN_ASSETS: Readonly<Record<Terrain, string>> = {
  open: "/assets/terrain/open-ground.svg",
  rough: "/assets/terrain/rough-ground.svg",
  "low-wall": "/assets/terrain/low-wall.svg",
  wall: "/assets/terrain/wall.svg",
  bush: "/assets/terrain/bush.svg",
  crevice: "/assets/terrain/crevice.svg",
  "outer-wall": "/assets/terrain/outer-wall.svg",
};

export const TERRAIN_ASSET_URLS = [...new Set(Object.values(TERRAIN_ASSETS))];

export const PROP_ASSETS = {
  crate: "/assets/terrain/crate.svg",
} as const;

/** Complete Phase 6 preload inventory: seven terrain textures plus the crate prop. */
export const ARENA_ASSET_URLS = [
  ...new Set([...TERRAIN_ASSET_URLS, ...Object.values(PROP_ASSETS)]),
];

const ROBOT_CLASSES: readonly RobotClass[] = ["rifle", "burst", "auto", "missile", "stealth"];
const POSTURES: readonly Posture[] = ["upright", "ducking", "crouching"];

const robotBodyUrl = (robotClass: RobotClass, posture: Posture) =>
  `/assets/robots/${robotClass}/body-${posture}.svg`;

export const ROBOT_BODY_ASSETS: Readonly<Record<RobotClass, Readonly<Record<Posture, string>>>> =
  Object.fromEntries(
    ROBOT_CLASSES.map((robotClass) => [
      robotClass,
      Object.fromEntries(POSTURES.map((posture) => [posture, robotBodyUrl(robotClass, posture)])),
    ]),
  ) as Record<RobotClass, Record<Posture, string>>;

export const ROBOT_TURRET_ASSETS: Readonly<Record<RobotClass, string>> = {
  rifle: "/assets/robots/rifle/turret.svg",
  burst: "/assets/robots/burst/turret.svg",
  auto: "/assets/robots/auto/turret.svg",
  missile: "/assets/robots/missile/turret.svg",
  stealth: "/assets/robots/stealth/turret.svg",
};

/**
 * Geometry contract of the generated robot sprites (viewBox units).
 * Body files are 128×128 with the ground anchor at (64,93); the turret file
 * is 96×96 with its pivot at the exact center, 1.18× readability scale baked
 * in. The turret mount point drops as the hull hunkers — `turretPivotY` is
 * the per-posture mount height in body space (matches each file's
 * `data-turret-pivot`).
 */
export const ROBOT_SPRITE_GEOMETRY = {
  bodyBox: 128,
  turretBox: 96,
  turretPivotY: { upright: 42, ducking: 50, crouching: 54 } as Readonly<Record<Posture, number>>,
} as const;

export const EFFECT_ASSETS = {
  muzzleFlash: "/assets/effects/muzzle-flash.svg",
  tracerBullet: "/assets/effects/tracer-bullet.svg",
  projectileMissile: "/assets/effects/projectile-missile.svg",
  projectileGrenade: "/assets/effects/projectile-grenade.svg",
  explosionSmall: "/assets/effects/explosion-small.svg",
  explosionLarge: "/assets/effects/explosion-large.svg",
  blastRing: "/assets/effects/blast-ring.svg",
  smokePuff: "/assets/effects/smoke-puff.svg",
  hitSpark: "/assets/effects/hit-spark.svg",
  dustMiss: "/assets/effects/dust-miss.svg",
  wreck: "/assets/effects/wreck.svg",
} as const;

export const MARKER_ASSETS = {
  selectionRing: "/assets/markers/selection-ring.svg",
  lastKnown: "/assets/markers/last-known.svg",
  scanLock: "/assets/markers/scan-lock.svg",
} as const;

export const EFFECT_ASSET_URLS = Object.values(EFFECT_ASSETS);
export const MARKER_ASSET_URLS = Object.values(MARKER_ASSETS);
export const MOVIE_MARKER_ASSET_URLS = [MARKER_ASSETS.lastKnown, MARKER_ASSETS.scanLock];
